apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-watcher-sa
  namespace: resource-management
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-watcher-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-watcher-rolebinding
subjects:
- kind: ServiceAccount
  name: kube-watcher-sa
  namespace: resource-management
roleRef:
  kind: ClusterRole
  name: kube-watcher-role
  apiGroup: rbac.authorization.k8s.io

---

