# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: resource-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      nodeSelector:
        is-management-node: "true"
      serviceAccountName: kube-controller-sa
      imagePullSecrets:
      - name: registry-cert
      containers:
      - name: controller
        image: $(IMAGE_REPOSITORY_ENDPOINT)/controller:tw-1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-secret
              key: api-key